<?php
/**
 * Created by PhpStorm.
 * User: ivan.li
 * Date: 9/5/2016
 * Time: 2:08 PM
 */

namespace App\Models;


use App\Models\DeletedRecordModels\DeletedCategory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $primaryKey = "subscription_id";
    protected $fillable = [
        "category_name", "user_id", "category_order", "report_task_id"
    ];
    public $timestamps = false;

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id', 'user_id');
    }

    public function products()
    {
        return $this->hasMany('App\Models\Product', 'category_id', 'category_id');
    }

    /**
     * back up category before deleting
     * @return bool|null
     */
    public function delete()
    {
        DeletedCategory::create(array(
            "content" => $this->toJson()
        ));
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}