<?php
/**
 * Created by PhpStorm.
 * User: ivan.li
 * Date: 9/5/2016
 * Time: 2:14 PM
 */

namespace App\Models;


use App\Models\DeletedRecordModels\DeletedProduct;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $primaryKey = "product_id";
    protected $fillable = [
        "product_name", "category_id", "user_id", "group_id", "product_orders", "report_task_id"
    ];
    public $timestamps = false;
    protected $appends = ["urls"];

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id', 'user_id');
    }

    public function category()
    {
        return $this->belongsTo('App\Models\Category', 'category_id', 'category_id');
    }

//    public function sites()
//    {
//        return $this->belongsToMany('App\Models\Site', 'product_sites', 'product_id', 'site_id')->withPivot('product_site_id');
//    }
    public function sites()
    {
        return $this->hasManyThrough('App\Models\Site', 'App\Models\ProductSite', 'product_id', 'site_id', 'product_id');
    }

    public function productSites()
    {
        return $this->hasMany('App\Models\ProductSite', 'product_id', 'product_id');
    }

    public function alert()
    {
        return $this->hasOne('App\Models\Alert', 'alert_owner_id', 'product_id');
    }

    /**
     * back up category before deleting
     * @return bool|null
     */
    public function delete()
    {
        DeletedProduct::create(array(
            "content" => $this->toJson()
        ));
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function getUrlsAttribute()
    {
        return array(
            "show" => route("product.show", $this->getKey()),
            "edit" => route("product.edit", $this->getKey()),
            "delete" => route("product.destroy", $this->getKey()),
            "alert" => route("alert.product.edit", $this->getKey()),
        );
    }
}